### ISSUE TITLE
using new lines with XML variables

### ISSUE THREAD

**Issue by richardwo** [refactoror/SelBlocks#24]
Trying to add some content to a text area using XML file for variables.
I want new lines to be included.
I tried the following:

```
<vars content="line 1
line 2
line 3"/>
```

Also used \n but neither works.

How can I add new lines with XML variables?

**Comment by refactoror** [comment]
This is really an XML question, which has its own rules about whitespace. When white space is part of the XML syntax, e.g., between tags, it is discarded by XML parsers and is not passed on to processing applications, like SelBlocks. Essentially, whitespace is treated as formatting of the XML document itself, rather than as part of the resulting content.

There are ways to encode whitespace, but is not always supported within attribute values. You can try:

```
<vars content="line 1&#x0A;line 2&#x0A;line 3"/>
```

I'm not sure what the Firefox XML parser will do with it.

**Comment by richardwo** [comment]
Thanks - using `&#x0A;` works fine for getting newline characters into Firefox.
